### ISSUE TITLE
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.

### ISSUE THREAD

**Issue by AlexxB31** [Raider-Arts/painter-megascan-link#7]
Hello, I had a manual install with Terminal as Admin on Windows 10:
Part of the message is:

"WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command."

I have no knowledge about this stuff, please let me know what it means.
(Current Substance Painter 2021)
Thanks!

**Comment by faggionluca** [comment]
Hello @AlexxB31 that is just a python stardard message telling you that a new version of pip is avaiable ([pip](https://pypi.org/project/pip/) is the the package installer for Python) you can safely ignore it. i hope the rest of the manual installation was successfull.

**Comment by faggionluca** [comment]
Anyway if the manual installation did not completed correctly you can try out the new version of the plugin [v0.3.0-beta](https://github.com/Raider-Arts/painter-megascan-link/releases/tag/v0.3.0-beta) that i've released today since it doesn't need any manual dependecies installation and should work just after you installed it just by coping the files!

**Comment by AlexxB31** [comment]
Thanks @darkimage for the infos. It was also working with the old version :) Thanks for the plugin.

**Comment by faggionluca** [comment]
Thank you for using it 😄
